config/routes.rb
Rails.application.routes.draw do
  require 'api'
  require "api_v2"
  require 'sidekiq/web'

  resources :sites
  resources :pages, path: "wiki" do
    collection do
      get :recent
      post :preview
    end
    member do
      get :comments
    end
  end
  resources :comments
  resources :notes do
    collection do
      post :preview
    end
  end

  root to: "home#index"

  devise_for :users, path: "account", controllers: {
      registrations: :account,
      sessions: :sessions,
      omniauth_callbacks: "users/omniauth_callbacks"
    }

  delete "account/auth/:provider/unbind" => "users#auth_unbind", as: 'unbind_account'
  post "account/update_private_token" => "users#update_private_token", as: 'update_private_token_account'

  resources :notifications, only: [:index, :destroy] do
    collection do
      post :clear
    end
  end

  resources :nodes

  get "topics/node:id" => "topics#node", as: 'node_topics'
  get "topics/node:id/feed" => "topics#node_feed", as: 'feed_node_topics', defaults: { format: 'xml' }
  get "topics/last" => "topics#recent", as: 'recent_topics'
  resources :topics do
    member do
      post :reply
      post :favorite
      delete :unfavorite
      post :follow
      delete :unfollow
      patch :suggest
      delete :unsuggest
    end
    collection do
      get :no_reply
      get :popular
      get :excellent
      get :feed, defaults: { format: 'xml' }
      post :preview
    end
    resources :replies
  end

  resources :photos
  resources :likes
  resources :jobs

  get "/search" => "search#index", as: 'search'

  namespace :cpanel do
    root to: "home#index"
    resources :site_configs
    resources :replies
    resources :topics do
      member do
        post :suggest
        post :unsuggest
        post :undestroy
      end
    end
    resources :nodes
    resources :sections
    resources :users
    resources :photos
    resources :pages do
      resources :versions, controller: :page_versions do
        member do
          post :revert
        end
      end
    end
    resources :comments
    resources :site_nodes
    resources :sites
    resources :locations
    resources :exception_logs do
      collection do
        post :clean
      end
    end
  end

  get "api" => "home#api", as: 'api'
  get "twitter" => "home#twitter", as: "twitter"

  mount RubyChina::API => "/"
  mount RubyChina::APIV2 => "/"

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)

  # WARRING! 请保持 User 的 routes 在所有路由的最后，以便于可以让用户名在根目录下面使用，而又不影响到其他的 routes
  # 比如 http://ruby-china.org/huacnlee
  get "users/city/:id" => "users#city", as: 'location_users'
  get "users" => "users#index", as: 'users'
  resources :users, path: "" do
    member do
      get :topics
      get :favorites
      get :notes
    end
  end

  match '*path', via: :all, to: 'home#error_404'
end

app/models/note.rb
# coding: utf-8
# 记事本
class Note
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::BaseModel
  include Redis::Objects

  field :title
  field :body
  field :word_count, type: Integer
  field :changes_count, type:  Integer, default: 0
  field :publish, type: Mongoid::Boolean, default: false
  belongs_to :user
  
  counter :hits, default: 0

  index user_id: 1
  index updated_at: -1

  scope :recent_updated, -> {  desc(:updated_at) }
  scope :published, -> {  where(publish: true) }

  before_save :auto_set_value
  def auto_set_value
    if !self.body.blank?
      self.title = self.body.split("\n").first[0..50]
      self.word_count = self.body.length
    end
  end

  before_update :update_changes_count
  def update_changes_count
    self.changes_count = 0 if self.changes_count.blank?
    self.inc(changes_count: 1)
  end

end

app/controllers/notes_controller.rb
# coding: utf-8
class NotesController < ApplicationController
  load_and_authorize_resource

  def index
    @notes = current_user.notes.recent_updated.paginate(page: params[:page], per_page: 20)
    set_seo_meta t('menu.notes')
  end

  def show
    @note =  Note.find(params[:id])
    @note.hits.incr(1)
    set_seo_meta("查看 &raquo; #{t("menu.notes")}")
  end

  def new
    @note = current_user.notes.build
    set_seo_meta("新建 &raquo; #{t('menu.notes')}")
  end

  def edit
    @note = current_user.notes.find(params[:id])
    set_seo_meta("修改 &raquo; #{t('menu.notes')}")
  end

  def create
    @note = current_user.notes.new(note_params)
    @note.publish = note_params[:publish] == '1'
    if @note.save
      redirect_to(@note, notice: t('common.create_success'))
    else
      render action: 'new'
    end
  end

  def update
    @note = current_user.notes.find(params[:id])
    if @note.update_attributes(note_params)
      redirect_to(@note, notice: t('common.update_success'))
    else
      render action: 'edit'
    end
  end

  def preview
    render text: MarkdownConverter.convert(params[:body])
  end

  def destroy
    @note = current_user.notes.find(params[:id])
    @note.destroy

    redirect_to(notes_url)
  end

  private

  def note_params
    params.require(:note).permit(:title, :body, :publish)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
  def render_node_topics_count(node)
    node.topics_count
  end

  def render_node_name(name, id)
    link_to(name, node_topics_path(id), class: 'node')
  end
  
  def note_title_tag(note, opts = {})
    opts[:limit] ||= 50
    return "" if note.blank?
    return "" if note.title.blank?
    truncate(note.title.gsub('#',''), length: opts[:limit])
  end
end

app/views/notes/_form.html.erb
<%= simple_form_for(@note) do |f| %>
  <fieldset>
    <%= render "shared/error_messages", target: @note %>

    <div class="editor-toolbar">
        <ul class="pills" style="clear:none;">
          <li class="edit active"><%= link_to(t("common.editor_toolbar_edit"), "#") %></li>
          <li class="preview"><%= link_to(t("common.editor_toolbar_preview"), "#") %></li>
        </ul>
    </div>

    <%= f.text_area :body, class: "span16", style: "height:500px" %>
    
    <div class="inputs-list">
      <label for="note_publish"><%= f.check_box :publish %> <%= t("common.public")%></label>
    </div>
    
    <p class="help-block">
      <%= t("notes.please_use") %> <a href="http://en.wikipedia.org/wiki/Markdown" target="_blank">Markdown</a> <%= t("notes.document_format_to_write") %>
    </p>
    <div style="margin-top:10px;">
      <%= f.submit t("common.save"), class: "btn btn-primary", 'data-disable-with' => t("common.saving") %>
      <a href="<%= notes_path %>" class="btn reset"><%= t("common.cancel") %></a>
    </div>
  </fieldset>
<% end %>

app/views/notes/_sidebar.zh-CN.html.erb
<div class="sidebar">
  <div class="box">
    <h2 class="title">记事本是什么？</h2>
    <p class="summary">这是一个基于云存储的网络记事本，你可以放心的把你的一些文本资料存放在此处。</p>
  </div>

  <% if ["new","edit"].index(params[:action]) %>
  <div class="box">
    <h2 class="title">提示</h2>
    <ul>
      <li>记事的第一行将自动成为标题</li>
      <li>超级链接会自动转换为可点击的状态</li>
      <li>目前只支持纯文本格式</li>
      <li>记事本的内容只有你自己才能看到</li>
    </ul>
  </div>
  <% end %>
</div>

app/views/notes/_sidebar.zh-TW.html.erb
<div class="sidebar">
  <div class="box">
    <h2 class="title">記事本是什麼？</h2>
    <p class="summary">這是一個基於雲端儲存的網路記事本，你可以放心的把你的一些文件資料存放在這裡。</p>
  </div>

  <% if ["new","edit"].index(params[:action]) %>
  <div class="box">
    <h2 class="title">提示</h2>
    <ul>
      <li>記事的第一行將自動成為標題</li>
      <li>超連結會自動轉換為可點擊的狀態</li>
      <li>目前只支援純文字格式</li>
      <li>記事本的內容只有你自己才能看到</li>
    </ul>
  </div>
  <% end %>
</div>

app/views/notes/edit.html.erb
<div class="notes box">
  <h2 class="title"><%= t("notes.edit_note")%></h2>
  <%= render 'form' %>
</div>

app/views/notes/index.html.erb
<div class="content">
  <div id="notes" class="box">
    <h2 class="title">我的记事本</h2>
    <div class="total">
      已有 <%= current_user.notes.count %> 条记事
      <a href="<%= new_note_path %>" class="btn btn-success">新建记事</a>
    </div>
    <% if @notes.blank? %>
      <div style="text-align:center; padding:60px 0;">你还没有创建过一个文件。</div>
    <% else %>
      <ul class="list">
      <% @notes.each do |note| %>
        <li>
          <div><a class="title" href="<%= note_path(note.id) %>"><i class="icon-stop"></i> <%= truncate(note.title.gsub('#',''), length: 50) %></a> <%= raw '<span class="label warning">公开</span>' if note.publish %></div>
          <div class="info">
            <%= note.word_count %> <%= t("notes.chars") %>, <%= sanitize t("notes.created_at", time: timeago(note.created_at)) %>, <%= note.changes_count %> <%= t("notes.times_edit") %>
          </div>
        </li>
      <% end %>
      </ul>
    <% end %>
    <%= will_paginate @notes %>
  </div>
</div>

<%= render "sidebar" %>

app/views/notes/new.html.erb
<div class="notes box">
  <h2 class="title"><%= t("notes.create_note")%></h2>
  <%= render 'form' %>
</div>

app/views/notes/show.html.erb
<div id="notes" class="box">
  <div class="note">
    <% if @note.publish %>
    <div class="pull-right urls">
      <em><%= t("notes.page_link")%></em> <input type="text" onclick="$(this).select();" value="<%= note_url(@note) %>" readonly="readonly" />
    </div>
    <% end %>
    <div class="info">
      <p>
        <%= raw '<span class="label warning">公开</span> ' if @note.publish %>
        共 <%= @note.word_count %> <%= t("notes.chars") %> • 由 <%= user_name_tag(@note.user) %> <%= sanitize t("notes.created_at", time: timeago(@note.created_at)) %> • <%= @note.hits %> <%= t("common.read_times")%> • <%= @note.changes_count %> <%= t("notes.times_edit") %>
        <% if owner? @note %>
          <%= link_to "", edit_note_path(@note), class: "icon small_edit", title: t("common.edit") %>
          <%= link_to "", note_path(@note), class: "icon small_delete",'data-confirm' => t("common.confirm_delete"), method: :delete, title: t("common.confirm_delete") %>
        <% end %>
      </p>
    </div>

    <div class="body markdown-body"><%= markdown(@note.body) %></div>
  </div>
</div>