config/routes.rb
Rails.application.routes.draw do
  require 'api'
  require "api_v2"
  require 'sidekiq/web'

  resources :sites
  resources :pages, path: "wiki" do
    collection do
      get :recent
      post :preview
    end
    member do
      get :comments
    end
  end
  resources :comments
  resources :notes do
    collection do
      post :preview
    end
  end

  root to: "home#index"

  devise_for :users, path: "account", controllers: {
      registrations: :account,
      sessions: :sessions,
      omniauth_callbacks: "users/omniauth_callbacks"
    }

  delete "account/auth/:provider/unbind" => "users#auth_unbind", as: 'unbind_account'
  post "account/update_private_token" => "users#update_private_token", as: 'update_private_token_account'

  resources :notifications, only: [:index, :destroy] do
    collection do
      post :clear
    end
  end

  resources :nodes

  get "topics/node:id" => "topics#node", as: 'node_topics'
  get "topics/node:id/feed" => "topics#node_feed", as: 'feed_node_topics', defaults: { format: 'xml' }
  get "topics/last" => "topics#recent", as: 'recent_topics'
  resources :topics do
    member do
      post :reply
      post :favorite
      delete :unfavorite
      post :follow
      delete :unfollow
      patch :suggest
      delete :unsuggest
    end
    collection do
      get :no_reply
      get :popular
      get :excellent
      get :feed, defaults: { format: 'xml' }
      post :preview
    end
    resources :replies
  end

  resources :photos
  resources :likes
  resources :jobs

  get "/search" => "search#index", as: 'search'

  namespace :cpanel do
    root to: "home#index"
    resources :site_configs
    resources :replies
    resources :topics do
      member do
        post :suggest
        post :unsuggest
        post :undestroy
      end
    end
    resources :nodes
    resources :sections
    resources :users
    resources :photos
    resources :pages do
      resources :versions, controller: :page_versions do
        member do
          post :revert
        end
      end
    end
    resources :comments
    resources :site_nodes
    resources :sites
    resources :locations
    resources :exception_logs do
      collection do
        post :clean
      end
    end
  end

  get "api" => "home#api", as: 'api'
  get "twitter" => "home#twitter", as: "twitter"

  mount RubyChina::API => "/"
  mount RubyChina::APIV2 => "/"

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)

  # WARRING! 请保持 User 的 routes 在所有路由的最后，以便于可以让用户名在根目录下面使用，而又不影响到其他的 routes
  # 比如 http://ruby-china.org/huacnlee
  get "users/city/:id" => "users#city", as: 'location_users'
  get "users" => "users#index", as: 'users'
  resources :users, path: "" do
    member do
      get :topics
      get :favorites
      get :notes
    end
  end

  match '*path', via: :all, to: 'home#error_404'
end

app/models/topic.rb
# coding: utf-8
require "auto-space"
class Topic
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::BaseModel
  include Mongoid::SoftDelete
  include Mongoid::CounterCache
  include Mongoid::Likeable
  include Mongoid::MarkdownBody
  include Redis::Objects
  include Mongoid::Mentionable

  field :title
  field :body
  field :body_html
  field :last_reply_id, type: Integer
  field :replied_at , type: DateTime
  field :source
  field :message_id
  field :replies_count, type: Integer, default: 0
  # 回复过的人的 ids 列表
  field :follower_ids, type: Array, default: []
  field :suggested_at, type: DateTime
  # 最后回复人的用户名 - cache 字段用于减少列表也的查询
  field :last_reply_user_login
  # 节点名称 - cache 字段用于减少列表也的查询
  field :node_name
  # 删除人
  field :who_deleted
  # 用于排序的标记
  field :last_active_mark, type: Integer
  # 是否锁定节点
  field :lock_node, type: Mongoid::Boolean, default: false
  # 精华帖 0 否， 1 是
  field :excellent, type: Integer, default: 0

  # 临时存储检测用户是否读过的结果
  attr_accessor :read_state

  belongs_to :user, inverse_of: :topics
  counter_cache name: :user, inverse_of: :topics
  belongs_to :node
  counter_cache name: :node, inverse_of: :topics
  belongs_to :last_reply_user, class_name: 'User'
  belongs_to :last_reply, class_name: 'Reply'
  has_many :replies, dependent: :destroy

  validates_presence_of :user_id, :title, :body, :node

  index node_id: 1
  index user_id: 1
  index last_active_mark: -1
  index likes_count: 1
  index suggested_at: 1
  index excellent: -1

  counter :hits, default: 0

  delegate :login, to: :user, prefix: true, allow_nil: true
  delegate :body, to: :last_reply, prefix: true, allow_nil: true

  # scopes
  scope :last_actived, -> {  desc(:last_active_mark) }
  # 推荐的话题
  scope :suggest, -> { where(:suggested_at.ne => nil).desc(:suggested_at) }
  scope :fields_for_list, -> { without(:body,:body_html) }
  scope :high_likes, -> { desc(:likes_count, :_id) }
  scope :high_replies, -> { desc(:replies_count, :_id) }
  scope :no_reply, -> { where(replies_count: 0) }
  scope :popular, -> { where(:likes_count.gt => 5) }
  scope :without_node_ids, Proc.new { |ids| where(:node_id.nin => ids) }
  scope :excellent, -> { where(:excellent.gte => 1) }

  def self.find_by_message_id(message_id)
    where(message_id: message_id).first
  end

  # 排除隐藏的节点
  def self.without_hide_nodes
    where(:node_id.nin => self.topic_index_hide_node_ids)
  end

  def self.topic_index_hide_node_ids
    SiteConfig.node_ids_hide_in_topics_index.to_s.split(",").collect { |id| id.to_i }
  end

  before_save :store_cache_fields
  def store_cache_fields
    self.node_name = self.node.try(:name) || ""
  end
  before_save :auto_space_with_title
  def auto_space_with_title
    self.title.auto_space!
  end

  before_create :init_last_active_mark_on_create
  def init_last_active_mark_on_create
    self.last_active_mark = Time.now.to_i
  end

  def push_follower(uid)
    return false if uid == self.user_id
    return false if self.follower_ids.include?(uid)
    self.push(follower_ids: uid)
    true
  end

  def pull_follower(uid)
    return false if uid == self.user_id
    self.pull(follower_ids: uid)
    true
  end

  def update_last_reply(reply, opts = {})
    # replied_at 用于最新回复的排序，如果帖着创建时间在一个月以前，就不再往前面顶了
    return false if reply.blank? && !opts[:force]
    
    self.last_active_mark = Time.now.to_i if self.created_at > 1.month.ago
    self.replied_at = reply.try(:created_at)
    self.last_reply_id = reply.try(:id)
    self.last_reply_user_id = reply.try(:user_id)
    self.last_reply_user_login = reply.try(:user_login)
    self.save
  end
  
  # 更新最后更新人，当最后个回帖删除的时候
  def update_deleted_last_reply(deleted_reply)
    return false if deleted_reply.blank?
    return false if self.last_reply_user_id != deleted_reply.user_id
    
    previous_reply = self.replies.where(:_id.nin => [deleted_reply.id]).recent.first
    self.update_last_reply(previous_reply, force: true)
  end

  # 删除并记录删除人
  def destroy_by(user)
    return false if user.blank?
    self.update_attribute(:who_deleted,user.login)
    self.destroy
  end

  def destroy
    super
    delete_notifiaction_mentions
  end

  def last_page_with_per_page(per_page)
    page = (self.replies_count.to_f / per_page).ceil
    page > 1 ? page : nil
  end

  # 所有的回复编号
  def reply_ids
    Rails.cache.fetch([self,"reply_ids"]) do
      self.replies.only(:_id).map(&:_id)
    end
  end

  def excellent?
    self.excellent >= 1
  end
end

app/controllers/cpanel/topics_controller.rb
# coding: utf-8
class Cpanel::TopicsController < Cpanel::ApplicationController

  def index
    @topics = Topic.unscoped.desc(:_id).includes(:user).paginate page: params[:page], per_page: 30

  end

  def show
    @topic = Topic.unscoped.find(params[:id])

  end


  def new
    @topic = Topic.new
  end

  def edit
    @topic = Topic.unscoped.find(params[:id])
  end

  def create
    @topic = Topic.new(params[:topic].permit!)

    if @topic.save
      redirect_to(cpanel_topics_path, notice: 'Topic was successfully created.')
    else
      render action: "new"
    end
  end

  def update
    @topic = Topic.unscoped.find(params[:id])

    if @topic.update_attributes(params[:topic].permit!)
      redirect_to(cpanel_topics_path, notice: 'Topic was successfully updated.')
    else
      render action: "edit"
    end
  end

  def destroy
    @topic = Topic.unscoped.find(params[:id])
    @topic.destroy_by(current_user)

    redirect_to(cpanel_topics_path)
  end

  def undestroy
    @topic = Topic.unscoped.find(params[:id])
    @topic.update_attribute(:deleted_at, nil)
    redirect_to(cpanel_topics_path)
  end

  def suggest
    @topic = Topic.unscoped.find(params[:id])
    @topic.update_attribute(:suggested_at, Time.now)
    CacheVersion.topic_last_suggested_at = Time.now
    redirect_to(cpanel_topics_path, notice: "Topic:#{params[:id]} suggested.")
  end

  def unsuggest
    @topic = Topic.unscoped.find(params[:id])
    @topic.update_attribute(:suggested_at, nil)
    CacheVersion.topic_last_suggested_at = Time.now
    redirect_to(cpanel_topics_path, notice: "Topic:#{params[:id]} unsuggested.")
  end
end

app/controllers/topics_controller.rb
# coding: utf-8
class TopicsController < ApplicationController
  load_and_authorize_resource only: [:new, :edit, :create, :update, :destroy,
                                     :favorite, :unfavorite, :follow, :unfollow, :suggest, :unsuggest]
  caches_action :feed, :node_feed, expires_in: 1.hours

  def index
    @suggest_topics = Topic.without_hide_nodes.suggest.limit(3)
    suggest_topic_ids = @suggest_topics.map(&:id)

    @topics = Topic.last_actived.without_hide_nodes.where(:_id.nin => suggest_topic_ids)
    @topics = @topics.fields_for_list.includes(:user)
    @topics = @topics.paginate(page: params[:page], per_page: 15, total_entries: 1500)

    set_seo_meta '', "#{Setting.app_name}#{t("menu.topics")}"
  end

  def feed
    @topics = Topic.recent.without_body.limit(20).includes(:node, :user, :last_reply_user)
    render layout: false
  end

  def node
    @node = Node.find(params[:id])
    @topics = @node.topics.last_actived.fields_for_list
    @topics = @topics.includes(:user).paginate(page: params[:page], per_page: 15)
    set_seo_meta "#{@node.name} &raquo; #{t("menu.topics")}", "#{Setting.app_name}#{t("menu.topics")}#{@node.name}", @node.summary
    render action: 'index'
  end

  def node_feed
    @node = Node.find(params[:id])
    @topics = @node.topics.recent.without_body.limit(20)
    render layout: false
  end

  %W(no_reply popular).each do |name|
    define_method(name) do
      @topics = Topic.send(name.to_sym).last_actived.fields_for_list.includes(:user)
      @topics = @topics.paginate(page: params[:page], per_page: 15, total_entries: 1500)

      set_seo_meta [t("topics.topic_list.#{name}"), t('menu.topics')].join(' &raquo; ')
      render action: 'index'
    end
  end

  def recent
    @topics = Topic.recent.fields_for_list.includes(:user)
    @topics = @topics.paginate(page: params[:page], per_page: 15, total_entries: 1500)
    set_seo_meta [t('topics.topic_list.recent'), t('menu.topics')].join(' &raquo; ')
    render action: 'index'
  end

  def excellent
    @topics = Topic.excellent.recent.fields_for_list.includes(:user)
    @topics = @topics.paginate(page: params[:page], per_page: 15, total_entries: 1500)

    set_seo_meta [t('topics.topic_list.excellent'), t('menu.topics')].join(' &raquo; ')
    render action: 'index'
  end

  def show
    @topic = Topic.without_body.find(params[:id])
    @topic.hits.incr(1)
    @node = @topic.node
    @show_raw = params[:raw] == '1'

    @per_page = Reply.per_page
    # 默认最后一页
    params[:page] = @topic.last_page_with_per_page(@per_page) if params[:page].blank?
    @page = params[:page].to_i > 0 ? params[:page].to_i : 1

    @replies = @topic.replies.unscoped.without_body.asc(:_id)
    @replies = @replies.paginate(page: @page, per_page: @per_page)
    
    check_current_user_status_for_topic
    set_special_node_active_menu
    
    set_seo_meta "#{@topic.title} &raquo; #{t("menu.topics")}"

    fresh_when(etag: [@topic, @has_followed, @has_favorited, @replies, @node, @show_raw])
  end
  
  def check_current_user_status_for_topic
    return false if not current_user
    
    # 找出用户 like 过的 Reply，给 JS 处理 like 功能的状态
    @user_liked_reply_ids = []
    @replies.each { |r| @user_liked_reply_ids << r.id if r.liked_user_ids.index(current_user.id) != nil }
    # 通知处理
    current_user.read_topic(@topic)
    # 是否关注过
    @has_followed = @topic.follower_ids.index(current_user.id) == nil
    # 是否收藏
    @has_favorited = current_user.favorite_topic_ids.index(@topic.id) == nil
  end
  
  def set_special_node_active_menu
    case @node.try(:id)
    when Node.jobs_id
      @current = ["/jobs"]
    end
  end

  def new
    @topic = Topic.new
    if !params[:node].blank?
      @topic.node_id = params[:node]
      @node = Node.find_by_id(params[:node])
      render_404 if @node.blank?
    end

    set_seo_meta "#{t('topics.post_topic')} &raquo; #{t('menu.topics')}"
  end

  def edit
    @topic = Topic.find(params[:id])
    @node = @topic.node

    set_seo_meta "#{t('topics.edit_topic')} &raquo; #{t('menu.topics')}"
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id
    @topic.node_id = params[:node] || topic_params[:node_id]

    if @topic.save
      redirect_to(topic_path(@topic.id), notice: t('topics.create_topic_success'))
    else
      render action: 'new'
    end
  end

  def preview
    @body = params[:body]

    respond_to do |format|
      format.json
    end
  end

  def update
    @topic = Topic.find(params[:id])
    if @topic.lock_node == false || current_user.admin?
      # 锁定接点的时候，只有管理员可以修改节点
      @topic.node_id = topic_params[:node_id]

      if current_user.admin? && @topic.node_id_changed?
        # 当管理员修改节点的时候，锁定节点
        @topic.lock_node = true
      end
    end
    @topic.title = topic_params[:title]
    @topic.body = topic_params[:body]

    if @topic.save
      redirect_to(topic_path(@topic.id), notice: t('topics.update_topic_success'))
    else
      render action: 'edit'
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy_by(current_user)
    redirect_to(topics_path, notice: t('topics.delete_topic_success'))
  end

  def favorite
    current_user.favorite_topic(params[:id])
    render text: '1'
  end
  
  def unfavorite
    current_user.unfavorite_topic(params[:id])
    render text: '1'
  end

  def follow
    @topic = Topic.find(params[:id])
    @topic.push_follower(current_user.id)
    render text: '1'
  end

  def unfollow
    @topic = Topic.find(params[:id])
    @topic.pull_follower(current_user.id)
    render text: '1'
  end

  def suggest
    @topic = Topic.find(params[:id])
    @topic.update_attributes(excellent: 1)
    redirect_to @topic, success: '加精成功。'
  end

  def unsuggest
    @topic = Topic.find(params[:id])
    @topic.update_attribute(:excellent, 0)
    redirect_to @topic, success: '加精已经取消。'
  end

  private

  def topic_params
    params.require(:topic).permit(:title, :body, :node_id)
  end
end

app/helpers/topics_helper.rb
# coding: utf-8
require 'digest/md5'
module TopicsHelper
  def format_topic_body(text)
    MarkdownTopicConverter.format(text)
  end

  def topic_use_readed_text(state)
    case state
    when true
      t("topics.have_no_new_reply")
    else
      t("topics.has_new_replies")
    end
  end

  def topic_favorite_tag(topic)
    return "" if current_user.blank?
    class_name = "bookmark"
    link_title = "收藏"
    if current_user && current_user.favorite_topic_ids.include?(topic.id)
      class_name = "bookmarked"
      link_title = "取消收藏"
    end

    link_to("", "#", class: "icon small_#{class_name}", title: link_title, rel: "twipsy",
            onclick: "return Topics.favorite(this);", 'data-id' => topic.id)
  end

  def topic_follow_tag(topic)
    return "" if current_user.blank?
    return "" if topic.blank?
    return "" if owner?(topic)
    class_name = "follow"
    if topic.follower_ids.include?(current_user.id)
      class_name = "followed"
    end
    icon = content_tag("i", "", class: "icon small_#{class_name}")
    followed = class_name == "followed"
    link_to(raw("#{icon} 关注"), "#", onclick: "return Topics.follow(this);", rel: "twipsy",
            'data-id' => topic.id, 'data-followed' => followed)
  end

  def topic_title_tag(topic)
    return t("topics.topic_was_deleted") if topic.blank?
    link_to(topic.title, topic_path(topic), title: topic.title)
  end

  def topic_excellent_tag(topic)
    return "" if !topic.excellent?
    content_tag(:i,"", title: "精华帖", class: "icon small_cert_on")
  end

  def render_topic_last_reply_time(topic)
    l((topic.replied_at || topic.created_at), format: :short)
  end

  def render_topic_created_at(topic)
    timeago(topic.created_at, class: "published")
  end

  def render_topic_last_be_replied_time(topic)
    timeago(topic.replied_at)
  end

  def render_topic_node_select_tag(topic)
    return if topic.blank?
    grouped_collection_select :topic, :node_id, Section.all,
                    :sorted_nodes, :name, :id, :name,
                    {value: topic.node_id, include_blank: true, prompt: "选择节点"}, style: "width:145px;"
  end
end

app/views/topics/_buttons.html.erb
<div class="tools pull-right">
  <% if admin? %>
    <% if !@topic.suggested_at.blank? %>
      <%= link_to raw("<i class='icon small_pin'></i> 取消"), unsuggest_cpanel_topic_path(@topic), 'data-confirm' => '确定要取消置顶么?', method: :post %>
    <% else %>
      <%= link_to raw("<i class='icon small_pin'></i> 置顶"), suggest_cpanel_topic_path(@topic), 'data-confirm' => '确定要置顶么?', method: :post %>
    <% end %>
    <% if !@topic.excellent? %>
      <%= link_to raw("<i class='icon small_cert'></i> 加精"), suggest_topic_path(@topic.id), title: "设为精华帖" , method: "patch", data: { confirm: "确定要设置成精华帖么？" } %>
    <% end %>
  <% end %>
  <%= topic_follow_tag(@topic) %>
  <%= likeable_tag(@topic) %>
  <%= topic_favorite_tag(@topic) %>
  <% if owner?(@topic) or admin? %>
    <%= link_to "", edit_topic_path(@topic), class: "icon small_edit", title: "修改本帖" %>
    <%= link_to "", topic_path(@topic.id), method: :delete, 'data-confirm' => t("common.confirm_delete"), class: "icon small_delete", title: "删除本帖" %>
  <% end %>
</div>
<%= social_share_button_tag h("#{@topic.title} via: @#{Setting.twitter_id} ") %>

app/views/topics/_editor_toolbar.html.erb
<div class="editor-toolbar">
  <div class="icons pull-right">
    <span class="dropdown dropdown-small" id="editor-toolbar-insert-code">
      <a href="#editor-toolbar-insert-code" data-toggle="dropdown" class="icon small_code" rel="twipsy" title="<%= t("topics.insert_codes") %>" href="#editor-toolbar-insert-code"></a>
      <ul class="dropdown-menu" role="menu">
        <%= insert_code_menu_items_tag %>
      </ul>
    </span>
    <%= link_to("", "#", id: "topic_add_image", rel: "twipsy", title: t("topics.add_image"), class: "icon small_image")%>
    <input type="file" id="topic-upload-images"/>
  </div>
  <ul class="pills" style="clear:none;">
    <li class="edit active"><%= link_to(t("common.editor_toolbar_edit"), "#") %></li>
    <li class="preview"><%= link_to(t("common.editor_toolbar_preview"), "#") %></li>
  </ul>
</div>

app/views/topics/_node_info.html.erb
<% if !node.blank? %>
  <div>
    <h2><%= node.name %></h2>
    <span class="total">共有 <%= render_node_topics_count(node) %> 个讨论主题</span>
    <div class="feed">
      <%= link_to("#{content_tag(:span, "", class: "icon share_icons_rss" )}".html_safe, feed_node_topics_url, title: "#{node.name} Feed") %>
    </div>
  </div>
  <div class="desc">
    <%= simple_format(node.summary) %>
  </div>
<% else %>
  <div class="sorts">
    <span class="lb">查看:</span>
    <ul>
      <li<%= " class=active" if action_name == "index"  %>><%= link_to "默认", topics_path %></li> /
      <li<%= " class=active" if action_name == "popular"  %>>
        <%= link_to raw("<i class='icon small_liked'></i> 优质帖子"), popular_topics_path, class: "popular" %>
      </li> /
      <li<%= " class=active" if action_name == "no_reply"  %>><%= link_to "无人问津", no_reply_topics_path, rel: 'nofollow' %></li> /
      <li<%= " class=active" if action_name == "recent"  %>><%= link_to "最新创建", recent_topics_path, rel: 'nofollow' %></li>
    </ul>
  </div>
<% end %>

app/views/topics/_sidebar_box_new_topic_tip.html.erb
<div id="topic-new-tip" class="box">
  <h2 class="title"><%= t("topics.tips_for_create_topic")%></h2>
  <span class="body help-block">
     <%= render_cell :topics, :reply_help_block %>
  </span>
</div>

app/views/topics/_sidebar_box_node_new_topic.html.erb
<% if can? :create, Topic %>
  <% if !@node.blank? %>
    <div class="box" style="text-align:center;">
      <h2 class="title"><%= link_to(@node.name,  node_topics_path(@node))%></h2>
      <%=  render_node_summary(@node) if ["new"].index(params[:action]) %>
      <div class="content">
        <%= link_to(t("topics.start_a_new_topic_button"), new_topic_path(node: @node.id), class: "btn btn-success") %>
      </div>

    </div>
  <% end %>
<% end %>

app/views/topics/_sidebar_for_topic_index.html.erb
<%= render "topics/sidebar_box_new_topic" %>
<%= render "topics/sidebar_box_newbie_info" %>
<%= render_cell :topics, :tips %>
<%= raw SiteConfig.topic_index_sidebar_html %>
<%= render_cell :topics, :sidebar_statistics %>

app/views/topics/index.html.erb
<div class="content">
  <div class="box box-gray">
    <div id="node-info">
      <%= render "topics/node_info", node: @node %>
    </div>

    <div class="topics">
      <% if @topics.current_page == 1 %>
        <% cache(@suggest_topics) do %>
          <%= render partial: "topics/topic", collection: @suggest_topics, locals: { suggest: true } %>
        <% end %>
      <% end %>
      <%= render partial: "topics/topic", collection: @topics, locals: { suggest: false } %>
    </div>
    <%= will_paginate @topics, inner_window: 2 %>

  </div>

  <% if controller_name == "topics" && action_name == "index" && !mobile? %>
    <%= render_cell :topics, :index_sections %>
    <%= render_cell :topics, :index_locations %>
  <% end %>

  <% if !@node.blank? %>
    <% content_for :node_feed_link do %>
      <%= auto_discovery_link_tag(:rss, feed_node_topics_url, title: "#{@node.name} 节点最新话题") %>
    <% end %>
  <% end %>

</div>

<% if current_user %>
<script type="text/javascript">
  var readed_topic_ids = <%= current_user.filter_readed_topics(@topics) %>;
  readed_topic_ids = readed_topic_ids.concat(<%= current_user.filter_readed_topics(@suggest_topics) %>);
  for (var i = 0; i < readed_topic_ids.length; i++) {
    topic_id = readed_topic_ids[i];
    $(".topic-"+ topic_id + " .right-info .count").addClass("state-true");
  }
</script>
<% end %>

<% if !mobile? %>
  <div class="sidebar">
    <%= render "topics/sidebar_for_topic_index" if action_name.in?(%w(index)) %>
    <%= render "topics/sidebar_for_topic_recent" if action_name.in?(%w(recent no_reply popular excellent)) %>
    <%= render "topics/sidebar_for_topic_node" if action_name == "node" %>
  </div>
<% end %>

app/views/topics/show.html.erb
<% content_for :scripts do %>
  <script type="text/javascript">
    Topics.replies_per_page = <%= @per_page %>;
    $(document).ready(function(){
      <% if admin? %>
        $("#replies .reply a.edit").css('display','inline-block');
      <% elsif current_user %>
        $("#replies .reply a.edit[data-uid='<%= current_user.id %>']").css('display','inline-block');
      <% end %>
      <% if current_user && !@user_liked_reply_ids.blank? %>
        Topics.checkRepliesLikeStatus([<%= @user_liked_reply_ids.join(",") %>]);
      <% end %>
    })
  </script>
<% end %>

<div class="content">
  <div id="topic-show" class="topics box hfeed">
    <div class="topic hentry">
      <%= render partial: "topics/topic_info", locals: { topic: @topic } %>
      <%= raw SiteConfig.before_topic_html %>
      <div class="body markdown-body entry-content">
        <%= sanitize_topic @topic.body_html %>
      </div>

      <% if @topic.excellent? %>
      <div class="excellent">
        <i class="icon small_cert_on"></i> 本帖已被设为精华帖！
        <% if admin? %>
        <div class="opts pull-right">
          <%= link_to "取消", unsuggest_topic_path(@topic.id), method: "delete" %>
        </div>
        <% end %>
      </div>
      <% end %>

      <%= raw SiteConfig.after_topic_html %>

      <%= render "buttons" %>
    </div>
  </div>

  <% if @replies.blank? %>
    <div class="no-result">
      <%= t("topics.no_replies") %>
    </div>
    <% else %>
    <div id="replies" class="box box-gray" data-last-floor="<%= @replies.count %>">
      <div class="total">
        共收到 <b><%= @topic.replies_count %></b> 条回复
      </div>
      <div class="items">
        <%= cache([@topic,params[:page],"raw:#{@show_raw}"]) do %>
          <%= render partial: "replies/reply", collection: @replies %>
        <% end %>
      </div>
      <%= will_paginate @replies, inner_window: 2, params: { anchor: 'replies' } %>
    </div>
  <% end %>

  <% if current_user %>
    <div id="reply" class="form box">
      <% if can? :create, Reply %>
        <%= render "editor_toolbar" %>
        <%= form_for(Reply.new, remote: true, url: topic_replies_path(@topic)) do |f| %>
          <%= f.text_area :body, class: "topic-editor span10", rows: "4", tabindex: "1" %>
          <div class="submit-buttons">
            <button type="submit" id="btn_reply" class="btn btn-primary" tabindex="2"><%= t("topics.submit_reply")%></button><br />
            <span class="help-inline" title="或者 Command + Enter">Ctrl+Enter</span>
          </div>

          <span class="body helpblock">
            <%= render_cell :topics, :reply_help_block %>
          </span>
        <% end %>
      <% else %>
        <div class="alert alert-info">
          当前设置新手用户不能在 22:00 ~ 9:00 发帖。
        </div>
      <% end %>
    </div>
  <% else %>
      <%= render partial: "topics/translation/need_login_to_reply" %>
  <% end %>
</div>

<% if !mobile? %>
  <div class="sidebar">
    <%= render "sidebar_box_node_new_topic" %>
    <%= render_cell :topics, :tips %>
    <%= render_cell :topics, :sidebar_for_node_recent_topics, { topic: @topic } %>
  </div>
<% end %>