config/routes.rb
Rails.application.routes.draw do
  require 'api'
  require "api_v2"
  require 'sidekiq/web'

  resources :sites
  resources :pages, path: "wiki" do
    collection do
      get :recent
      post :preview
    end
    member do
      get :comments
    end
  end
  resources :comments
  resources :notes do
    collection do
      post :preview
    end
  end

  root to: "home#index"

  devise_for :users, path: "account", controllers: {
      registrations: :account,
      sessions: :sessions,
      omniauth_callbacks: "users/omniauth_callbacks"
    }

  delete "account/auth/:provider/unbind" => "users#auth_unbind", as: 'unbind_account'
  post "account/update_private_token" => "users#update_private_token", as: 'update_private_token_account'

  resources :notifications, only: [:index, :destroy] do
    collection do
      post :clear
    end
  end

  resources :nodes

  get "topics/node:id" => "topics#node", as: 'node_topics'
  get "topics/node:id/feed" => "topics#node_feed", as: 'feed_node_topics', defaults: { format: 'xml' }
  get "topics/last" => "topics#recent", as: 'recent_topics'
  resources :topics do
    member do
      post :reply
      post :favorite
      delete :unfavorite
      post :follow
      delete :unfollow
      patch :suggest
      delete :unsuggest
    end
    collection do
      get :no_reply
      get :popular
      get :excellent
      get :feed, defaults: { format: 'xml' }
      post :preview
    end
    resources :replies
  end

  resources :photos
  resources :likes
  resources :jobs

  get "/search" => "search#index", as: 'search'

  namespace :cpanel do
    root to: "home#index"
    resources :site_configs
    resources :replies
    resources :topics do
      member do
        post :suggest
        post :unsuggest
        post :undestroy
      end
    end
    resources :nodes
    resources :sections
    resources :users
    resources :photos
    resources :pages do
      resources :versions, controller: :page_versions do
        member do
          post :revert
        end
      end
    end
    resources :comments
    resources :site_nodes
    resources :sites
    resources :locations
    resources :exception_logs do
      collection do
        post :clean
      end
    end
  end

  get "api" => "home#api", as: 'api'
  get "twitter" => "home#twitter", as: "twitter"

  mount RubyChina::API => "/"
  mount RubyChina::APIV2 => "/"

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)

  # WARRING! 请保持 User 的 routes 在所有路由的最后，以便于可以让用户名在根目录下面使用，而又不影响到其他的 routes
  # 比如 http://ruby-china.org/huacnlee
  get "users/city/:id" => "users#city", as: 'location_users'
  get "users" => "users#index", as: 'users'
  resources :users, path: "" do
    member do
      get :topics
      get :favorites
      get :notes
    end
  end

  match '*path', via: :all, to: 'home#error_404'
end

app/controllers/cpanel/home_controller.rb
# coding: utf-8
class Cpanel::HomeController < Cpanel::ApplicationController
  def index
    @recent_topics = Topic.recent.limit(5)
  end
end

app/controllers/home_controller.rb
# coding: utf-8
class HomeController < ApplicationController
  def index
    @excellent_topics = Topic.excellent.recent.fields_for_list.includes(:user).limit(20).to_a

    fresh_when(etag: [@excellent_topics, SiteConfig.index_html])
  end

  def api
  end

  def twitter
  end
  
  def error_404
    render_404
  end
end

app/views/home/api.html.erb
<div class="box">
  <h1>Ruby China API 目录</h1>
  <p>下面是简单的 API 路由列表, 具体请参考源代码 <a href="https://github.com/ruby-china/ruby-china/blob/master/app/grape/api.rb" target="_blank">api.rb</a></p>
  <table class="table">
    <thead>
      <tr>
        <th>Method</th>
        <th>URL</th>
      </tr>
    </thead>
    <tbody>
    <% RubyChina::API.routes.each do |route| %>
      <tr>
        <td><%= route.route_method %></td>
        <% route_path = route.route_path.gsub("(.:format)",".json") %>
        <td><%= request.protocol %><%= Setting.domain %><%= route.route_path.gsub("(.:format)",".json") %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/home/index.html.erb
<%= raw SiteConfig.index_html %>

<div class="home_suggest_topics box box-gray">
  <h2>社区精华帖</h2>
  <div class="topics">
    <%= render partial: "topics/topic", collection: @excellent_topics, locals: { suggest: false } %>
  </div>
  <div class="more">
    <%= link_to "查看更多精华帖...", excellent_topics_path %>
  </div>
</div>
<% if !mobile? %>
  <%= render_cell :topics, :index_sections %>
  <%= render_cell :topics, :index_locations %>
<% end %>

app/views/home/twitter.html.erb
<%= raw SiteConfig.twitter_page_html %>